baseURL: 'https://serghei.blog/'
uglyurls: true

languageCode: ru
defaultContentLanguage: ru

title: Сергей Яковлев

refLinksErrorLevel: WARNING

googleAnalytics: G-G3XCZPK59N

author:
  name: Serghei Iakovlev
  email: mail@serghei.blog
  github: sergeyklay
  twitter: egreps
  location: 'Kyiv, Ukraine'

permalinks:
  posts: '/:section/:year/:month/:day/:slug'
  dramas: '/:section/:year/:month/:day/:slug'
  narratives: '/:section/:year/:month/:day/:slug'
  poems: '/:section/:year/:month/:day/:slug'
  pages: '/:slug'

social:
  twitter: egreps

markup:
  highlight:
    noClasses: false
  goldmark:
    parser:
      attribute:
        block: true

module:
  hugoVersion:
    extended: true
    min: '0.95.0'

  imports:
    - path: github.com/sergeyklay/gohugo-theme-ed
