baseURL: 'https://serghei.blog/'
uglyurls: true

languageCode: ru
defaultContentLanguage: ru

title: Сергей Яковлев
enableRobotsTXT: true

refLinksErrorLevel: WARNING

minify:
  disableXML: true
  tdewolff:
    html:
      keepQuotes: true

disableKinds:
  - RSS

taxonomies:
  tag: tags

outputs:
  home: [HTML, Atom, JSONFEED, JSON, MANIFEST, humanstxt]
  section: [HTML, Atom, JSONFEED]
  page: [HTML]
  taxonomy: [HTML]
  term: [HTML]

outputFormats:
  Atom:
    name: Atom
    mediaType: text/xml
    baseName: feeds/feed.atom
    rel: alternate
    isPlainText: false
    isHTML: false
    noUgly: true
    permalinkable: false
  JSONFEED:
    name: JsonFeed
    mediaType: application/feed+json
    baseName: feeds/feed
    rel: alternate
    isPlainText: true
    isHTML: false
    noUgly: false
  MANIFEST:
    name: Manifest
    mediaType: application/manifest+json
    baseName: manifest
    rel: manifest
    isPlainText: true
    isHTML: false
    noUgly: false
    notAlternative: true
  humanstxt:
    mediaType: text/plain
    baseName: humans
    rel: author
    isPlainText: true
    isHTML: false
    noUgly: true
    permalinkable: false
    notAlternative: true

mediaTypes:
  text/xml:
    suffixes:
      - xml
  application/feed+json:
    suffixes:
      - json
  application/manifest+json:
    suffixes:
      - webmanifest

sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5

author:
  name: Serghei Iakovlev
  email: mail@serghei.blog
  github: sergeyklay
  twitter: egreps
  location: 'Kyiv, Ukraine'

permalinks:
  posts: '/:section/:year/:month/:day/:slug'
  dramas: '/:section/:year/:month/:day/:slug'
  narratives: '/:section/:year/:month/:day/:slug'
  poems: '/:section/:year/:month/:day/:slug'
  pages: '/:slug'

markup:
  highlight:
    noClasses: false
  goldmark:
    parser:
      attribute:
        block: true

frontmatter:
  lastmod:
    - lastmod
    - ':git'
    - date
    - publishDate

module:
  hugoVersion:
    extended: true
    min: '0.95.0'

  imports:
    - path: github.com/sergeyklay/gohugo-theme-ed
