description: Персональный блог Сергея Яковлева
keywords:
  - язык программирования
  - грамматики
  - грамматика
  - компиляторы
  - парсеры
  - сканеры

copyright: Copyright (c) 2018-2022 Сергей Яковлев
colorScheme: ''
tagline: 'Мой блокнот, мастерская, место где я делюсь своим опытом и мыслями'

footer: >
      &copy; Сергей Яковлев, 2018-{year}.
      Если не указано иного, всё содержимое сайта доступно под лицензией
      <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.ru" target="_blank" rel="noopener noreferrer">
        CC BY-NC-SA 4.0
      </a>.

mainSections:
  - posts
  - dramas
  - narratives
  - poems

dateformat: ':date_long'
dateFormatToc: 2006.01.02

readmore: true
feedSize: 25
recentPostsSize: 5
botpoisonPublicKey: pk_f07df795-ca43-494c-a3b1-362ac4380433

contact:
  formAction: 'https://submit-form.com/ccPnq0Ur'
  emailSubject: Contact form submission
  thanksUrl: /thanks.html

assets:
  logo: /img/blog-logo.jpg

seo:
  publisher: Serghei Iakovlev
  anonymizeIp: true

search:
  maxSummaryLength: 100
  languages:
    - en
    - ru
