# Built with Jekyll 3.8.0

# Site settings
title:       'Сергей Яковлев'
tagline:     'Мой блокнот, мастерская, место где я делюсь своим опытом и мыслями'
description: 'Персональный блог Сергея Яковлева'
keywords:    'phalcon, zephir, языки, грамматика, грамматика, компиляторы'
url:         'https://serghei.blog'
baseurl:     ''

# SEO optimization
seo:
  ga: UA-85434340-4

# About/contact
author:
  name:  'Сергей Яковлев'
  email: 'egrep.no-spam.protonmail.ch'

github_username: sergeyklay

# Color scheme. Options: red, orange, magenta, cyan, blue, brown
color-scheme:

# Set encoding to UTF-8
encoding: utf-8

# Collections for pages and posts
collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /post/:year/:month/:day/:slug.html

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-feed

pagination:
  enabled:      true
  debug:        false
  per_page:     5
  limit:        0
  sort_reverse: true
  sort_field:   'date'
  collection:   'posts'
  permalink:    '/page-:num/'
  title:        ':title (страница :num)'
  category:     'posts'
  tag:          ''
  locale:       ''
  extension:    'html'
  indexpage:    'index'
  trail:
    before: 2
    after:  2

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:          true
  footnote_nr:       1
  entity_output:     as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:        1..6
  smart_quotes:      lsquo,rsquo,ldquo,rdquo
  enable_coderay:    false

# Contact form
contact:
  form_action:      'https://formspree.io/xbjjeboj'
  confirmation_url: '/thanks.html'
  email_subject:    'Contact form submission'

# Exclusions from the final site
exclude:
  - optional
  - vendor
  - Gemfile
  - Gemfile.lock
  - backstop_data
  - backstop.json
  - serve
  - LICENSE
  - README.md
  - CNAME
  - src

include:
  - _redirects
