baseURL = 'https://serghei.blog/'
uglyurls = true

languageCode = 'ru'
defaultContentLanguage = 'ru'
title = 'Сергей Яковлев'
theme = 'ed'
enableRobotsTXT = true

disableKinds = ['RSS']

[outputs]
  home = [ 'HTML', 'Atom', 'humanstxt' ]

[outputFormats.humanstxt]
  mediaType = 'text/plain'
  baseName = 'humans'
  rel = 'author'
  isPlainText = true
  isHTML = false
  noUgly = true
  permalinkable = false

[outputFormats.Atom]
  name = 'Atom'
  mediaType = 'text/xml'
  baseName = 'feeds/feed.atom'
  rel = 'alternate'
  isPlainText = false
  isHTML = false
  noUgly = true
  permalinkable = false

[mediaTypes]
  [mediaTypes.'text/xml']
    suffixes = ['xml']

[author]
  name = 'Serghei Iakovlev'
  email = 'mail@serghei.blog'
  github = '@sergeyklay'
  location = 'Kyiv, Ukraine'

[languages]
  [languages.ru]
    weight = 1
    languageDirection = 'ltr'
    languageName = 'Russian'

[permalinks]
    posts = '/:section/:year/:month/:day/:slug'
    dramas = '/:section/:year/:month/:day/:slug'
    narratives = '/:section/:year/:month/:day/:slug'
    poems = '/:section/:year/:month/:day/:slug'
    pages = '/:slug'

[params]
  description = 'Персональный блог Сергея Яковлева'
  copyright = 'Copyright (c) 2018-2022 Сергей Яковлев'
  colorScheme = ''
  tagline = 'Мой блокнот, мастерская, место где я делюсь своим опытом и мыслями'
  footer = """
    © Сергей Яковлев, 2018-2022.
    Если не указано иного, всё содержимое сайта доступно под лицензией
    <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.ru" target="_blank" rel="noopener noreferrer">
      CC BY-NC-SA 4.0
    </a>."""
  mainSections = ['posts', 'dramas', 'narratives', 'poems']
  postMeta = ['date']
  dateformat = 'January 02, 2006'
  dateFormatFeed = '2006-01-02T15:04:05Z'
  readmore = true
  feedSize = 25

  [params.assets]
    # TODO: Add logo
    logo = '/img/open-graph-logo.png' # Logo image, relative to ./assets
    logo_width = 200
    logo_height = 200

[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'Блог'
    url = '/'
    weight = -20
  [[menu.main]]
    identifier = 'contact'
    name = 'Контактная форма'
    url = '/contact.html'
    weight = 1
  [[menu.main]]
    identifier = 'about'
    name = 'Обо мне'
    url = '/about.html'
    weight = 2
  [[menu.main]]
    identifier = 'github'
    name = 'GitHub профиль'
    url = 'https://github.com/sergeyklay/'
    weight = 20
    [menu.main.params]
      external = true

[markup]
  [markup.highlight]
    style = 'monokailight'
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
