backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow
media_folder: "/assets/images"

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

collections:
  - name: "post"
    label: "Post"
    folder: "_posts"
    sort: "date:desc"
    create: true
    slug: "{{ year }}-{{ month }}-{{ day }}-{{ fields.slug }}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string", tagname: "h1" }
      - { label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mm:ss"}
      - { label: "Image", name: "featured_image", widget: "image", required: false }
      - { label: "Excerpt", name: "excerpt", widget: "string" }
      - { label: "TOC", name: "toc", widget: "markdown", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Slug", name: "slug", widget: "string" }

  - name: "page"
    label: "Page"
    folder: "_pages"
    sort: "title:asc"
    create: true
    slug: "{{ slug }}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "page" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string", required: false }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Image", name: "featured_image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
