** Лингвистики Панини
*** Грамматика Панини

   Грамматика Панини (Pāṇini -- предположительно около V века до н. э.) пыталась
вывести полную, максимально лаконичную и подкрепленную теоретической частью
систему анализа грамматической структуры санскрита. Говоря простым языком --
формализовать системный и непротиворечивый подход для грамматического анализа
санскрита. Она является основанием всех традиционных и современных систем
анализа санскрита и заслужила не малый интерес с исторической и теоретической
точки зрения. Западная теория грамматики испытывала влияние грамматики Панини на
каждом этапе своего развития на протяжении двух последних веков.

   В начале 19 века, сторонники сравнительного подхода, не без помощи Блумфилда,
увидели в этой грамматике принципы морфологического анализа. Леонард Блумфилд
является одним из выдающихся лингвистов XX века. Он известен трудами по
индоевропеистике, тагальскому языку, алгонкинским языкам, общей морфологии,
общей теории языка и является одним из основателей дескриптивного направления
структурной лингвистики.

*** Индийская грамматическая традиция

*** Метод грамматического анализа

*** Морфология и синтаксис

*** Фонология и фонетика

# Local Variables:
# ispell-local-dictionary: "russian"
# End:
