** Лингвистики Панини
*** Грамматика Панини

   Грамматика Панини (Pāṇini -- предположительно около V века до н. э.) пытается
вывести полный, максимально лаконичный и подкрепленный теоретической частью
согласованный анализ грамматичской системы санскрита. Говоря простым языком --
формализовать системный и непротиворечивый подход для грамматического анализа
санскрита. Она является основанием всех традиционных и современных систем
анализа санскрита и заслужила не малый интерес с исторической и теоритеческой
точки зрения.

   Западная теория грамматики испытывала влияние грамматики Панини на каждом
этапе своего развития на протяжении двух последних веков. Компаративисты
(стороники сравнительного подхода) начала 19 века увидели в этой грамматике
принципы морфологического анализа. Леонард Блумфилд, один из выдающихся
лингвистов XX века, известный трудами по индоевропеистике, общей теории языка и
один из основателей дескриптивного направления структурной лингвистики

*** Индийская грамматическая традиция

*** Метод грамматического анализа

*** Морфология и синтаксис

*** Фонология и фонетика

# Local Variables:
# ispell-local-dictionary: "russian"
# End:
