** Лингвистики Панини
*** Грамматика Панини

   Одним из первых, широко известных лингвистов принято считать Панини (Pāṇini),
жившего предположительно около V века до н. э. и ставшего одним из предтечей
современной структурной лингвистики, порождающей грамматики, семиотики и
логики. Вклад Панини в современное языковедение настолько велик, что даже
существует отдельная область -- паниниведение. А его сборник глагольных корней
санскрита до сих пор переиздается и используется студентами Индии. Панини
составил первую в истории Индии нормативную грамматику санскрита, исчерпывающе
описывающую фонетику, морфологию и синтаксис языка. Грамматика Панини пытается
вывести полную, максимально лаконичную и подкрепленную теоретической частью
систему анализа грамматической структуры санскрита. Говоря простым языком --
формализовать системный и непротиворечивый подход для грамматического анализа
санскрита. Она является основанием всех традиционных и современных систем
анализа санскрита и заслужила не малый интерес с исторической и теоретической
точки зрения. Западная теория грамматики испытывала влияние грамматики Панини на
каждом этапе своего развития на протяжении двух последних веков. В начале 19
века, сторонники сравнительного подхода, увидели в этой грамматике принципы
морфологического анализа. А выдающийся лингвист XX века, Леонард Блумфилд
(Leonard Bloomfield), известный трудами по индоевропеистике, тагальскому языку,
алгонкинским языкам, общей морфологии и общей теории языка, использовал
грамматику Панини в своей классической работе по моделированию алгонкинской
грамматики. Современная лингвистика признает грамматику Панини как наиболее
полную, порождающую грамматику любого языка и продолжает применять технические
аспекты впервые выведенные Панини по сей день.

*** Индийская грамматическая традиция

*** Метод грамматического анализа

*** Морфология и синтаксис

*** Фонология и фонетика

# Local Variables:
# ispell-local-dictionary: "russian"
# End:
