** Лингвистики Панини

   Одним из первых, широко известных лингвистов принято считать Панини (Pāṇini),
жившего предположительно около V века до н. э. и ставшего одним из предтечей
современной структурной лингвистики, порождающей грамматики, семиотики и
логики. На сегодняшний день о Панини мало что достоверно известно. Панини жил в
государстве Гандхара на севере Индии. Учился в городе Таксила, известном
богатыми традициями языкознания. Древние индусы помещали Панини в число ведийсих
мудрецов риши и приписывали его трудам руку Шивы. Панини составил первую в
истории Индии нормативную грамматику санскрита, исчерпывающе описывающую
фонетику, морфологию и синтаксис языка, что и является предметом данной
статьи.

*** Грамматика Панини

   Грамматика Панини пытается вывести полную, максимально лаконичную и
подкрепленную теоретической частью систему анализа грамматической структуры
санскрита. Говоря простым языком -- формализовать системный и непротиворечивый
подход для грамматического анализа санскрита. Она является основанием всех
традиционных и современных систем анализа санскрита и заслужила не малый интерес
с исторической и теоретической точки зрения. Западная теория грамматики
испытывала влияние грамматики Панини на каждом этапе своего развития на
протяжении двух последних веков. В начале 19 века, сторонники сравнительного
подхода, увидели в этой грамматике принципы морфологического анализа. А
выдающийся лингвист XX века, Леонард Блумфилд (Leonard Bloomfield), известный
трудами по индоевропеистике, тагальскому языку, алгонкинским языкам, общей
морфологии и общей теории языка, использовал грамматику Панини в своей
классической работе по моделированию алгонкинской грамматики.

   Вклад Панини в современное языковедение настолько велик, что даже существует
отдельная область -- паниниведение. А его сборник глагольных корней санскрита до
сих пор переиздается и используется студентами Индии. Современная лингвистика
признает грамматику Панини как наиболее полную, порождающую грамматику языка из
всех когда-либо написанных и продолжает применять технические аспекты впервые
выведенные Панини по сей день.

*** Индийская грамматическая традиция

*** Метод грамматического анализа

*** Морфология и синтаксис

*** Фонология и фонетика
*** Библиография

  - **The Encyclopedia of Language and Linguistics. P. Kiparsky**
    https://web.stanford.edu/~kiparsky/Papers/encycl.pdf
  - **Pāṇini. Wikipedia**
    https://en.wikipedia.org/wiki/P%C4%81%E1%B9%87ini
  - **Leonard Bloomfield. Wikipedia**
    https://en.wikipedia.org/wiki/Leonard_Bloomfield

# Local Variables:
# ispell-local-dictionary: "russian"
# End:
