name: CI

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - '2.4.x'
          - '2.5.x'
          - '2.6.x'

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        architecture: 'x64'

    - name: Install blog dependencies using Ruby ${{ matrix.ruby }}
      run: |
        gem install bundler
        bundle install

    - name: Build & test
      run: |
        bundle exec jekyll build -d _site
        bundle exec htmlproofer ./_site --only-4xx --check-favicon --check-html
