name: CI

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - '2.4.x'
#          - '2.3.8'
#          - '2.4.9'
#          - '2.5.7'

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        architecture: 'x64'

    - name: Run a one-line script
      run: echo Hello, world!

    - name: Run a multi-line script
      run: ruby --version
