name: CI

on:
  - push
  - pull_request

jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby:
          - '2.6.x'
          - '2.7.x'
          - '3.0.x'

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - uses: actions/cache@v2
        id: bundle-cache
        with:
          path: ~/.bundle
          key: ruby-${{ matrix.ruby }}

      - name: Install blog dependencies using Ruby ${{ matrix.ruby }}
        run: |
          gem install bundler
          bundle install --jobs "$(getconf _NPROCESSORS_ONLN)" --retry 3

      - name: Build static files
        run: bundle exec jekyll build -d _site

      - name: Test
        run: bundle exec htmlproofer ./_site --only-4xx --check-favicon --check-html
