name: CI

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - '2.4.x'
          - '2.5.x'
          - '2.6.x'

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        architecture: 'x64'

    - name: Install blog dependencies using Ruby ${{ matrix.ruby }}
      run: bundle install

    - name: Run a multi-line script
      run: ruby --version
